### ISSUE TITLE
Корректное отображение всех маркеров на области видимости карты

### ISSUE THREAD

**Issue by dentikhomirov** [2gis/mobile-sdk-ios-demo#161]
Добрый день!
Есть ли у Вас аналог GMSCoordinateBounds (GoogleMaps), чтобы при известном количестве точек на карте делать автоматическое приближение/отдаление так, чтобы все маркеры отображались на карте?

**Comment by lagner** [comment]
Привет. 
Аналог этой функции у нас это [calcPosition](https://docs.2gis.com/ru/ios/sdk/reference/2.6/calcPosition(camera%3Ageometry%3Atilt%3Abearing%3Apadding%3ApositionPoint%3Asize%3A)) 
Из всех точек которые надо вписать в область собирается геометрия, и дальше функция вычисляет положение камеры при котором все объекты войдут в видимую область экрана. Дальше с этой информацией можно переместить камеру через сеттер, либо запустить перелет `map.camera.move(calculatedCameraPosition)`

**Comment by dentikhomirov** [comment]
А какую геометрию нужно создавать? Я пробовал создавать PolygonGeomtery, на вход передавал параметры вида [[GeoPoint]], то есть у меня был один массив, в котором был еще один массив. У меня возвращаемое значение камеры не могло определить стартовые точки у камеры, у них было значение Nan. В итоге приложение крашилось

**Comment by lagner** [comment]
Не стоит использовать полигон. Из произвольных точек он может получиться какой-нибудь вывернутый, с самопересечениями и т.д. Это создает сложности, геометрия может быть не валидна.
Для того чтобы посчитать область нам фактически нужен только массив точек, а это Polyline (просто массив вершин)

**Comment by dentikhomirov** [comment]
Да, это в целом работает, но в одном случае из 5 получаю вот такую ошибку, когда пытаюсь использовать метод move у камеры

libc++abi: terminating with uncaught exception of type std::runtime_error: Cannot create camera move controller: position is invalid: {"geo_point":{"lat":

Во всех тестовых запусках используются одни и те же точки (к слову, их всего две)

**Comment by lagner** [comment]
Интересно. Не наблюдали такого поведения у себя. 
А можешь поделиться кусочком кода/точками как ты это воспроизводишь? Чем быстрее мы сможем это подебажить, тем быстрее поправим.

**Comment by dentikhomirov** [comment]
Точки:
    - latitude : 56.63979299999998
    - longitude : 47.90120700000001

    - latitude : 56.642174
    - longitude : 47.84265499999999

Код:

let polylineGeometry = PolylineGeometry(points: attributes.markers.map { $0.point.geoPoint })
var cameraPosition = calcPosition(camera: map.camera, geometry: polylineGeometry)
map.camera.move(position: cameraPosition, time: 0.4, animationType: .linear)

**Comment by lagner** [comment]
Спаибо.
Попробуем воспроизвести и разобраться

**Comment by maxal9999** [comment]
@dentikhomirov Привет. Тут проблема в том, что в момент, когда ты вызываешь calcPosition, то карта еще до конца не инициализирована, следовательно, размер камеры нулевой.
Как вариант, можно подписаться на изменение размера камеры
https://docs.2gis.com/ru/ios/sdk/reference/4.1/Camera#nav-lvl1--sizeChannel
и когда размер уже ненулевой, то вызывать calcPosition и перелет.
