### ISSUE TITLE
Невозможно задать произвольную ширину маркера/кластера через cluster.iconWidth = <значение>

### ISSUE THREAD

**Issue by yavl** [2gis/mobile-sdk-ios-demo#162]
**Как воспроизвести:**
1. Открыть демо проект "Динамическая кластеризация" Clustering/ClusteringDemoViewModel.swift
2. Поменять строчку `cluster.setIcon(icon: self.scooterModel)` на `cluster.iconWidth = 35.0`
3. Запустить

**Что ожидалось:**
Иконка хотя бы немного увеличилась по тапу на кластер.

**Что происходит:**
Если значение iconWidth 35.0: размер иконки остаётся прежним.
Если значение 40.0: на девайсе iPhone 12 (+в симуляторе тоже) - размер иконки увеличивается, на симуляторе iPhone SE 3 - остается прежним.

Также если в `func renderCluster(cluster: SimpleClusterObject) -> SimpleClusterOptions {}` вместо `iconWidth: LogicalPixel(30.0)` вписать `iconWidth: LogicalPixel(19.0)`, и вместо `cluster.setIcon(icon: self.scooterModel)` вставить `cluster.iconWidth = 20.0`, размер иконки поменяется сильно больше, чем на 5% - на iPhone 12 (для iPhone SE 3 видимо другие значения нужно подставить). Вроде должно быть, что iconWidth: LogicalPixel - это просто любой размер который можно задать, а не шажками. В документации не нашел инфо о том почему может так происходить, возможно баг?

**Comment by lagner** [comment]
Привет. 
У нас действительно есть _особенность_ при работе с размерами для растровых картинок. Суть: оно работает только кратно оригинальному размеру в пикселях. 
Т.е. у тебя есть картинка 32х32, ты хочешь увеличить ее до 70х70, но в итоге получишь 64х64.

Мы понимаем что поведение не самое очевидное, но такое ограничение у нас сейчас в движке. И переделывать это не самая срочная сейчас задача т.к. обойти со сторыны приложения очень просто:
- сначала масштабировать картинку как тебе нужно, а потом уже передавать ее в карту
- использовать векторные картинки в SVG. 

Я бы вообще сказал что векторные изображения имеют в данном случае много плюсов. При растягивании растровой картинки ты сильно теряешь в качестве. А если еще и неправильно почитать пропорцию, картинка превращается в странное мыло. На вектор же таких ограничений нет. Выстявлять можно любые размеры.

**Comment by yavl** [comment]
Теперь понятно, спасибо!

**Comment by lagner** [comment]
Раз подробности выяснили, тред закрою. Если будут еще какие-то вопросы можно открывать новый :)
