### ISSUE TITLE
Краш приложения, когда пересоздаём карту

### ISSUE THREAD

**Issue by DimaDontsov** [2gis/mobile-sdk-ios-demo#178]
**iOS SDK 2.8**
Запустил демо-проект.
Открыл первую вкладку и вернулся обратно в меню.
Открыл также первую вкладку и приложение падает.
Проблема происходит именно при отрисовке mapView.
Я пробовал вызывать mapFactory и не выводить mapView на экран VC - всё норм.
Те же самые проблемы встречаю в своём проекте, который использует **iOS SDK 2.8**

**Comment by maxal9999** [comment]
Проблема в том, что на M1 OpenGL падает, если собрать приложение под симулятор. Решится, когда в версии 5.0.0 переедем на Apple Metal.

**Comment by 1encore** [comment]
@maxal9999 @DimaDontsov поставил на свой проект 5.0.0-beta.2 ничем не помогло, все так же крашится
