### ISSUE TITLE
Краш при повторном запуске карты

### ISSUE THREAD

**Issue by 1encore** [2gis/mobile-sdk-ios-demo#187]
текст ошибки: `libc++abi: terminating with uncaught exception of type std::runtime_error: Reinitialization is not allowed.`
запускаю с эмулятора, iOS 15.5
версия sdk 2.8.0 - 2.8.1

<img width="1265" alt="image" src="https://user-images.githubusercontent.com/23492419/193451722-9e1347e7-feb4-49a9-bc67-bae69d9a0329.png">

**Comment by 1encore** [comment]
повтор: https://github.com/2gis/mobile-sdk-ios-demo/issues/178

**Comment by 1encore** [comment]
после обновлении на 5.0.0 (переезд на Apple Metal) должно было решиться, но проблема все та же

**Comment by maxal9999** [comment]
Привет. А тут проблема не в Apple Metal, а в том, что Container инициализируются в 2 экземплярах. Ты запускаешь код из демо? Или какой то свой проект?

**Comment by 1encore** [comment]
@maxal9999 привет, свой проект, точнее это либа для Flutter

**Comment by maxal9999** [comment]
Нельзя создавать более двух экземпляров Container в рамках одного процесса. То есть надо создать один экземпляр, а уже через него создавать карты, справочники и тд.

**Comment by 1encore** [comment]
@maxal9999 изначально на андройде двойная инициализация работала без проблем, поэтому я почему-то решил что это должно и работать и на iOS-е, это ограничение со стороны ОС?

**Comment by maxal9999** [comment]
Странно. Вообще, это кроссплатформенное ограничение, то есть и на Андроиде такое тоже не должно работать. Проверим.

**Comment by maxal9999** [comment]
Пора закрывать, спустя год) Короче, на Android у нас создается синглтон, а на iOS - нет. В будущих версиях приведем к одному виду.
