### ISSUE TITLE
app crashes after passing the route by navigation

### ISSUE THREAD

**Issue by raheem29** [2gis/mobile-sdk-ios-demo#188]
libc++abi: terminating with uncaught exception of type MarkovProcessor::TranslateError: Translate error: No match context "RouteEndHappyNewYear" to any rule in grammar
terminating with uncaught exception of type MarkovProcessor::TranslateError: Translate error: No match context "RouteEndHappyNewYear" to any rule in grammar

**Comment by lagner** [comment]
Hi @raheem29 

It's known issue. We are working on it. It'll be fixed by next patch release ASAP. 

Thank you for you feedback.

**Comment by lagner** [comment]
The bug has been fixed. You can check with the latest SDK version
