### ISSUE TITLE
Кэширование карты

### ISSUE THREAD

**Issue by 1encore** [2gis/mobile-sdk-ios-demo#189]
В самом приложении 2ГИС-а есть возможность скачивать карту конкретных городов, есть ли такая возможность в данном SDK?

**Comment by lagner** [comment]
Да, есть возможность работать c offline базами, но только в full  версии
https://docs.2gis.com/ru/ios/sdk/overview

Так же возможность скачивать базы выключена по умолчанию. Поэтому нужно отдельно об этом договариваться при получении ключа к SDK.
