### ISSUE TITLE
 SimpleClusterObject не меняет иконку

### ISSUE THREAD

**Issue by yadik64** [2gis/mobile-sdk-ios-demo#202]
```swift
                     for position in clusterPositions {
                        let objects = childCollection?.clusteringObjects(position: position)
                        
                        for object in objects ?? [] {
                            if let cluster = object as? SimpleClusterObject,
                               let annotation = (cluster.objects.last?.userData as? ChildAnnotation)  {
                                
                                let uiImage = await YClusterAnnotationView(image: annotation.image,
                                                                     count: Int(cluster.objectCount))
                                    .snapshot()
                                let icon = view.imageFactory.make(image: uiImage)
                                print(cluster.userData)
                                cluster.setIcon(icon: icon)
                            }
                        }
                    }
``` 
В методе print я вижу правильный ID который сохранил при создании кластера. Но иконка у кластера не меняется. Пробовал разные варианты, но изменить иконку не выходит.

**Comment by maxal9999** [comment]
Вот есть пример кода, где установка иконки работает.
https://github.com/2gis/mobile-sdk-ios-demo/blob/master/app/Views/DemoPages/Clustering/ClusteringDemoViewModel.swift#L178-L185

Если все еще есть ошибка, то создайте ветку от нашего демоаппа с вашим примером - посмотрим.

**Comment by maxal9999** [comment]
Да, ошибку локально воспроизвел. Спасибо за обращение. Взяли в работу, в 7.4.0 будет исправлена.

**Comment by yadik64** [comment]
А когда ориентировочно ждать версию 7.4.0?

**Comment by yadik64** [comment]
> Да, ошибку локально воспроизвел. Спасибо за обращение. Взяли в работу, в 7.4.0 будет исправлена.
А когда ориентировочно ждать версию 7.4.0?

**Comment by maxal9999** [comment]
Через недели 2.

**Comment by yarovoyDeveloper** [comment]
> Через недели 2.

Еще ожидается версия  7.4.0 с этим исправлением?

**Comment by maxal9999** [comment]
7.4.0 вышла, да. Все исправлено.
