### ISSUE TITLE
Повтор Lottie анимации

### ISSUE THREAD

**Issue by yadik64** [2gis/mobile-sdk-ios-demo#203]
Добрый день, в вашем проекте есть пример с Lottie анимацией. Но она там отрабатывает один раз и останавливается. Мне же надо добавить анимацию пульсации которая зациклена. В AppleMap я реализовал как CALayer и добавил к маркеру, для YandexMapKit дизайнер создал мне анимированный png.  
Анимированный png с DGis остался без анимации, дизайнер передал мне Lottie json файл но он отрабатывает один раз и останавливается. Я не нашел возможности его зациклить. Есть ли такая возможность?

**Comment by maxal9999** [comment]
Добрый день. Такая возможность есть, но не в последней версии. Появится в 7.4.0.
