### ISSUE TITLE
dgissdk.key 

### ISSUE THREAD

**Issue by ygboy1986** [2gis/mobile-sdk-ios-demo#210]
Hello, the project now needs to integrate the map. When I downloaded the demo and ran it, it prompted that the file dgissdk.key was missing. Please give me a solution. Thank you.
![WeChat06220d68af6741d5af40adcd438d6133](https://github.com/2gis/mobile-sdk-ios-demo/assets/8225211/6c9b58a1-e790-40c0-9e0a-f1fbfbd6152f)

**Comment by lagner** [comment]
Hello!
There is [a part](https://github.com/2gis/mobile-sdk-ios-demo?tab=readme-ov-file#getting-api-keys) in readme about it. Please follow the instructions to have the key provided. The key is unique for your installation.
