### ISSUE TITLE
Смена позиции у кластеризирующихся маркеров

### ISSUE THREAD

**Issue by DmitriqPanteleev** [2gis/mobile-sdk-ios-demo#216]
Добрый день, есть коллекция маркеров которые инициализируются через MapObjectManager.withClustering. Маркеры в данной имеют необычное поведение при смене их свойства position. Для обычной коллекции маркеров поведение вполне нормальное, но у кластеризирующихся есть проблема:
- Карта инициализируется, MapObjectManager.withClustering инициализируется, в него добавляются маркеры
- Меняем position одного из маркеров
- Зумимся к измененному маркеру и он перерисовывается на то место, где находился при инициализации карты
Если после смены position одного из маркеров, наоборот, отзумиться и собрать их в кластер, а потом снова увеличить зум, то результат будет абсолютно такой же. 
Вот форк с изменениями для воспроизведения данной проблемы: https://github.com/DmitriqPanteleev/mobile-sdk-ios-demo 
Сначала необходимо нажать на кнопку "Change one marker", а потом следовать любому из флоу, описанных выше. Данная проблема присутствует как на версии 7.4.1, так и на 10.1.0
Также прикладываю наглядно запись:
[IMG_2864.MP4.zip](https://github.com/2gis/mobile-sdk-ios-demo/files/14007039/IMG_2864.MP4.zip)
Буду крайне благодарен за своевременный ответ и помощь!

**Comment by maxal9999** [comment]
Добрый день. Прошу прощения, что долго отвечали. Действительно, это баг, исправим в ближайших версиях.

**Comment by DmitriqPanteleev** [comment]
Добрый день, уведомляю, что в версии 10.2.0 ситуация не изменилась

**Comment by maxal9999** [comment]
Привет. В 10.3.0 фикс залетел - можешь проверять.

**Comment by DmitriqPanteleev** [comment]
Привет, благодарю за оперативность

Пн, 6 мая 2024 г. в 14:53, Alexander Maksimovskiy ***@***.***
