### ISSUE TITLE
Не отображается карта на реальном устройстве

### ISSUE THREAD

**Issue by AmV1to** [2gis/mobile-sdk-ios-demo#219]
Добрый день. Подскажите, пожалуйста, в чём может быть проблема: запускаю карты на реальном устройстве, но карта не отображается — просто белый экран. На симуляторе всё работает.

![screen](https://github.com/2gis/mobile-sdk-ios-demo/assets/123501417/54ab6bc8-4b1b-4a23-bfbd-b3e353e22aaf)

Вот логи:
![photo_2024-02-21_16-01-54](https://github.com/2gis/mobile-sdk-ios-demo/assets/123501417/af9d1ee1-7226-431e-97f4-64c4f8546fc2)

**Comment by mariarti91** [comment]
Приветствую!
А девайс как в сеть ходит? не через VPN?

**Comment by AmV1to** [comment]
Добрый день, подключался не через VPN

**Comment by AmV1to** [comment]
Добрый день, я разобрался, теперь все работает нормально
