### ISSUE TITLE
как добавить dgissdk.key

### ISSUE THREAD

**Issue by AndrRok** [2gis/mobile-sdk-ios-demo#220]
"add the key file dgissdk.key to the application root." Как это сделать? 
<img width="353" alt="image" src="https://github.com/2gis/mobile-sdk-ios-demo/assets/105282006/42b0272a-8897-445c-b6c5-4a833c569965">
через touch  dgissdk.key получается так

**Comment by maxal9999** [comment]
Привет. Если открыть сейчас demo , то сборка даже не пройдет, потому что файл по проекту прикреплен, но физически его нет. Его нужно скопировать в mobile-sdk-ios-demo/app/dgissdk.key

**Comment by maxal9999** [comment]
https://docs.2gis.com/ru/ios/sdk/overview
Вот тут описан процесс получения ключа.

**Comment by AndrRok** [comment]
> https://docs.2gis.com/ru/ios/sdk/overview Вот тут описан процесс получения ключа.

привет, его уже прислали по почте в виде ключа -  ba25****-e8d8-411f-****-e6fbcb2***18. А откуда скопировать dgissdk.key? "Его нужно скопировать в mobile-sdk-ios-demo/app/dgissdk.key"

**Comment by maxal9999** [comment]
Обратись еще раз в тех поддержку - должны прислать именно файл ключа dgissdk.key

**Comment by AndrRok** [comment]
> Обратись еще раз в тех поддержку - должны прислать именно файл ключа dgissdk.key

Оказалось, что в пробном периоде не предоставляется доступ к мобильному SDK. Спасибо
