### ISSUE TITLE
Координаты по клику по карте

### ISSUE THREAD

**Issue by magnit033** [2gis/mobile-sdk-ios-demo#227]
Добрый день. 

Подскажите пожалуйста, как получить координаты (долготу и широту) по клику по карте. Не смог найти подобный функционал в документации.

Спасибо.

**Comment by mariarti91** [comment]
Добрый день.

Изначально клики в карту работают в экранных координатах. Например [тут](https://docs.2gis.com/ru/ios/sdk/examples/map#nav-lvl1--%D0%9F%D0%BE%D0%BB%D1%83%D1%87%D0%B5%D0%BD%D0%B8%D0%B5_%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2_%D0%BF%D0%BE_%D1%8D%D0%BA%D1%80%D0%B0%D0%BD%D0%BD%D1%8B%D0%BC_%D0%BA%D0%BE%D0%BE%D1%80%D0%B4%D0%B8%D0%BD%D0%B0%D1%82%D0%B0%D0%BC) описано как по клику в карту получить объекты. Из всего примера тут интересны две строчки, для получения точки в экранных координатах.

После того как точка в экранных координатах получена. Нужно воспользоваться [projection](https://docs.2gis.com/ru/ios/sdk/reference/10.5/BaseCamera#nav-lvl1--var%20projection) для перевода экранных координат в геокоординаты. 

Тут стоит помнить что projection нельзя взять один раз и использовать постоянно, так как он генерирует проекции для текущего состояния карты. при необходимости превратить экранные координаты в географические (или наоборот) нужно брать из камеры новый объект projection
