### ISSUE TITLE
Не меняется стиль карты через код стиля

### ISSUE THREAD

**Issue by ArlanDaulen** [2gis/mobile-sdk-ios-demo#233]
Задача такая: По кнопке менять стиль карты - светлый и темный. Создал пользовательские стили светлой и темной темы с кодами light, dark, и переместил в ios/Assets/. На iOS когда вызываю mapView.appearance = .universal(Theme(name: "dark")), не меняется. Подскажите как изменить стиль по кнопке?

**Comment by ArlanDaulen** [comment]
@maxal9999

**Comment by maxal9999** [comment]
Привет. mapView.appearance = .universal(Theme(name: "dark")) - отвечает за переключение темы внутри одних стилей. в iOS/Assets не поможет добавить - нужно явно задавать в Map. 
Пример в демо есть
https://github.com/2gis/mobile-sdk-ios-demo/blob/master/app/Views/Root/RootViewFactory.swift#L256-L264

**Comment by maxal9999** [comment]
Не совсем так.
https://docs.2gis.com/ru/mapgl/styles/overview/mobile-sdk#nav-lvl1--Создание_проекта

Если кратко, то в styles.2gis.com есть 2 шаблона стилей SDK. ВОт нужно создать на их основе свои кастомные стиле, и при выгрузке указать 2 стиля (для светлой и темной темы). Скачать архив, в котором будут обе темы.

**Comment by 1encore** [comment]
@maxal9999 проблема исчерпана, большое спасибо!
